export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const AUTH_SYSTEM_ERROR = 'LOGIN_SYSTEM_ERROR';
export const AUTH_LOADING = 'AUTH_LOADING';
export const LOGOUT = 'LOGOUT';
export const COOKIE_CHECKED = 'COOKIE_CHECKED';